WebApplication/Models/Animal.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace WebApplication.Models
{
    public class Animal
    {
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string AnimalId { get; set; }
        public string Name { get; set; }
        public string ScientificName { get; set; }
    }
}

WebApplication/Controllers/AnimalController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication.IRepository;
using System.Threading.Tasks;
using Newtonsoft.Json;
using WebApplication.Models;
using WebApplication.ViewModel;
using X.PagedList;



namespace WebApplication.Controllers
{
    [Route("api/[controller]")]
    public class AnimalController : Controller
    {
        private readonly IAnimalRepository _AnimalRepository;

        public AnimalController(IAnimalRepository AnimalRepository)
        {
            _AnimalRepository = AnimalRepository;
        }

        [HttpGet("list")]
        public Task<string> Get()
        {
            return this.GetAnimals();
        }

        private async Task<string> GetAnimals()
        {
            var animals = await _AnimalRepository.Get();
            return JsonConvert.SerializeObject(animals);
        }

        [HttpGet("{id}")]
        public Task<string> Get(string id)
        {
            return this.GetAnimal(id);
        }

        private async Task<string> GetAnimal(string id)
        {
            var animal = await _AnimalRepository.Get(id) ?? new Animal();
            return JsonConvert.SerializeObject(animal);
        }

        [HttpPost]
        public IActionResult Post()
        {
            return Redirect("index");
        }

        [HttpPut]
        public IActionResult Put()
        {
            return Redirect("index");
        }

        [HttpDelete("{id}")]
        public async Task<bool> Delete(string id)
        {
            if (string.IsNullOrEmpty(id)) return false;
            bool result = await _AnimalRepository.Remove(id);
            return result;
        }

        [HttpGet("index")]
        public IActionResult Index(AnimalViewModel animalVM)
        {
            var pageNumber = (animalVM.Pnumber == 0) ? 1 : animalVM.Pnumber;
            var pageSize = 10;
            var animals = _AnimalRepository.GetAll().ToPagedList(pageNumber, pageSize);
            animalVM.Animals = animals;
            return View(animalVM);
        }
    }
}

WebApplication/Views/Animal/Index.cshtml
@model AnimalViewModel
@{
    ViewBag.Title = "Animales";
}
<div id="principal">
    <div class="body-wrapper container">
        <h2>Animales</h2>
        <div>
            <button class="btn btn-primary" 
                type="button" onclick="location.href='@Url.Action("Create","Animal")'">
                <i class="fa fa-plus-circle"></i>
            </button>
        </div>
        <table id="animals_table" class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Nombre Científico</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var animal in Model.Animals)
                {
                    <tr>
                        <td>@animal.Name</td>
                        <td>@animal.ScientificName</td>
                        <td style="text-align: center;">
                            <button class="btn btn-primary" onclick="editarAnimal('@animal.AnimalId');">
                                <i class="fa fa-pencil"></i>
                            </button>
                            <button class="btn btn-danger" onclick="eliminarAnimal('@animal.AnimalId');">
                                <i class="fa fa-times-circle"></i>
                            </button>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
@section Scripts{
    <script>
    function editarAnimal(id) {
        window.location.href = '/api/animal/' + id + '/edit/';
    }

    function eliminarAnimal(id) {
        $.ajax({
            url: "/api/animal/" + id + "/",
            type: 'DELETE',
            async: false,
            success: function() {
                window.location.href = '@Url.Action("Index","Animal")';
            }
        });
    }
    </script>
}