WebApplication/Controllers/MapController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text.Encodings.Web;
using System.Net.Http;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebApplication {

    public class MapController : Controller {
        public IActionResult Index() {
            return View();
        }
    }
    
}

WebApplication/Views/Shared/Index.cshtml
@model IndexModel
@{
    ViewData["Title"] = "Bosque Protector";
}
@section Style{
  <link href='/css/stations.css' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Prata' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>     
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
}

<div class="row equal">
 	<div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 plus-station" style="margin-bottom: 15px">
		<div class="new_station_button">
			<a data-toggle="modal" href="#station_modal"><i class="material-icons" id="plus-icon">
				add_circle_outline
			</i></a>
		</div>
	</div>
</div>

<!-- Modal form-->
<div class="modal fade" id="station_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" style="margin-top: 2px" onclick="closeModal(1)">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="modal_label">Nueva Estación</h4>
			</div>
			<div class="modal-body">
				<div class="row">
				<form id="form">
					<div class="form-group col-lg-4 col-md-4 col-sm-4 col-xs-12">
						<label class="control-label">Nombre:</label>
						<input id="name" name="name" class="form-control" type="text"/>
					</div>
					<div class="form-group col-lg-4 col-md-4 col-sm-4 col-xs-12">
						<label class="control-label">Estación Juego:</label>
						<input id="game_station" name="game_station" class="form-control" type="number"/>
					</div>
					<div class="form-group col-lg-4 col-md-4 col-sm-4 col-xs-12">
						<label class="control-label">API Key:</label>
						<input id="api_key" name="api_key" class="form-control" type="text"/>
					</div>
					<div class="form-group col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<label class="control-label">Latitud:</label>
						<input id="latitude" name="latitude" class="form-control" type="text"/>
					</div>
					<div class="form-group col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<label class="control-label">Longitud:</label>
						<input id="longitude" name="longitude" class="form-control" type="text"/>
					</div>
					<div class="form-group col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<label class="control-label">Versión de Android:</label>
						<input id="android_version" name="android_version" class="form-control" type="text"/>
					</div>
					<div class="form-group col-lg-6 col-md-6 col-sm-6 col-xs-12">
						<label class="control-label">Versión de Servicios:</label>
						<input id="services_version" name="services_version" class="form-control" type="text"/>
					</div>
					<input id="db_id" type="hidden"/>
				</form>
				</div>
			</div>
			<div class="modal-footer">
				<button id="save" class="btn btn-primary" onclick="saveStation()">Guardar</button>
				<button id="cancel" class="btn btn-default" onclick="closeModal(1)">Cancelar</button>
			</div>
		</div>
	</div>
</div>

<!-- Modal alert-->
<div class="modal fade" id="alert_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header alert-danger">
				<button type="button" class="close" style="margin-top: 1px" onclick="closeModal(2)">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="modal_alert_label">ADVERTENCIA</h4>
			</div>
			<div class="modal-body">
				<p>Se borrará la estación y todos sus sensores, así como todos los datos relacionados a ellos.
					Esta acción no puede revertirse. ¿Desea continuar?
				</p>
				<input id="st_id" type="hidden"/>
			</div>
			<div class="modal-footer">
				<button id="accept" class="btn btn-danger" onclick="deleteStation()">Aceptar</button>
				<button id="cancel" class="btn btn-default" onclick="closeModal(2)">Cancelar</button>
			</div>
		</div>
	</div>
</div>

@section ScriptsIndex {
  <script src="~/js/stations.js"></script>
}

WebApplication/Views/Shared/_AjaxGrid.cshtml
@model string

<div class="mvc-grid" data-source-url="@Model">
</div>

WebApplication/Views/Shared/_Grid.cshtml
@using NonFactors.Mvc.Grid;

@model IGrid

<div@(Html.Raw(Model.Name != null ? " id=\"" + Model.Name + "\"" : "")) class="mvc-grid">
    <table class="table @Model.CssClasses"@Model.Attributes>
        <thead>
            <tr>
                @foreach (IGridColumn column in Model.Columns)
                {
                    String filterableClass = column.IsFilterable == true ? "filterable" : null;
                    String sortableClass = column.IsSortable == true ? "sortable" : null;

                    <th class="@filterableClass @sortableClass @column.CssClasses"
                        data-name="@column.Name"
                        data-filter="@column.IsFilterable"
                        data-filter-name="@column.FilterName"
                        data-filter-multi="@column.IsMultiFilterable"
                        data-filter-first-type="@column.Filter?.First?.Type"
                        data-filter-first-val="@column.Filter?.First?.Value"
                        data-filter-operator="@column.Filter?.Operator"
                        data-filter-second-type="@column.Filter?.Second?.Type"
                        data-filter-second-val="@column.Filter?.Second?.Value"
                        data-sort="@column.IsSortable"
                        data-sort-order="@column.SortOrder"
                        data-sort-first="@column.FirstSortOrder">
                        @if (column.IsSortable == true)
                        {
                            <span class="mvc-grid-header-title @column.SortOrder.ToString().ToLower()">@column.Title</span>
                        }
                        else
                        {
                            <span class="mvc-grid-header-title">@column.Title</span>
                        }
                        @if (column.IsFilterable == true)
                        {
                            String filterApplied = column.Filter != null && (column.Filter.First != null || column.Filter.Second != null) ? "applied" : "";
                            <span class="mvc-grid-filter @filterApplied"></span>
                        }
                    </th>
                }
            </tr>
        </thead>
        <tbody>
            @if (Model.Rows.Any())
            {
                foreach (IGridRow<Object> row in Model.Rows)
                {
                    <tr class="@row.CssClasses">
                        @foreach (IGridColumn column in Model.Columns)
                        {
                            <td class="@column.CssClasses">@column.ValueFor(row)</td>
                        }
                    </tr>
                }
            }
            else if (Model.EmptyText != null)
            {
                <tr class="mvc-grid-empty-row">
                    <td class="mvc-grid-empty" colspan="@Model.Columns.Count()">
                        @Model.EmptyText
                    </td>
                </tr>
            }
        </tbody>
        @if (Model.FooterPartialViewName != null)
        {
            <tfoot>
                @Html.Partial(Model.FooterPartialViewName, Model)
            </tfoot>
        }
    </table>
    @if (Model.Pager != null)
    {
        @Html.Partial(Model.Pager.PartialViewName, Model.Pager)
    }
</div>

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="cache-control" content="no-store" />
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>@ViewBag.Title</title>
        <link href="~/css/site.css" rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link href="~/css/w3.css" rel="stylesheet">     
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/bootstrap-dialog.min.css">
        <link rel="stylesheet" href="~/css/layout.css">
        <link rel="stylesheet" href="~/css/select2.min.css"/>
        
        @RenderSection("Style", required: false)
    </head>
    <body>  
        <div class="nav-side-menu navbar-dark">
            <div class="brand">
                <a href="/home">
                <img src="/images/logo-white.png"/>
                </a>
            </div>
            <button class="navbar-toggler toggle-btn" data-toggle="collapse" data-target="#menu-content"><span class="navbar-toggler-icon"></span></button>
            <div class="menu-list">
                <ul id="menu-content" class="menu-content collapse out">
                    <li id="login-side" class="login"></li>
                    <li data-toggle="collapse" data-target="#monitoreo" class="collapsed">
                        <a href="#"><i class="fa fa-dashboard fa-lg"></i> Monitoreo <span class="arrow"></span></a>
                    </li>
                    <ul class="sub-menu collapse" id="monitoreo">
                        <li><a href='@Url.Action("Index","Home")'><div>Estaciones</div></a></li>
                        <li><a href='@Url.Action("Index","Audios")'><div>Audios</div></a></li>
                        <li><a href='@Url.Action("Index","Image")'><div>Imágenes</div></a></li>
                        <li><a href='@Url.Action("Index","Map")'><div>Mapa</div></a></li>
                    </ul>

                    <li data-toggle="collapse" data-target="#historicos" class="collapsed">
                        <a href="#"><i class="fa fa-bar-chart"></i>Históricos<span class="arrow"></span></a>
                    </li>
                    <ul class="sub-menu collapse" id="historicos">
                        <li><a href='@Url.Action("ByHour","HistoricalData")'>Por hora</a></li>
                        <li><a href='@Url.Action("ByDate","HistoricalData")'>Por día</a></li>
                        <li><a href='@Url.Action("ByMonth","HistoricalData")'>Por mes</a></li>                               
                        <li><a href='@Url.Action("ByDateStation","HistoricalData")'>Entre estaciones</a></li>                       
                    </ul>
                    <li>
                        <a href='@Url.Action("Index","Alert")'><i class="fa fa-bell fa-lg"></i> <div>Alertas</div> </a>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","Incident")'><i class="fa fa-exclamation-triangle" ></i> <div>Incidentes</div> </a>
                    </li>
                    <li data-toggle="collapse" data-target="#administracion" class="collapsed">
                        <a href="#"><i class="fa fa-wrench fa-lg"></i> Administración <span class="arrow"></span></a>
                    </li>
                    <ul class="sub-menu collapse" id="administracion">
                        <li><a href='@Url.Action("Index","Users")'><div>Usuarios</div></a></li>
                    </ul>
                    <li>
                        <a href='@Url.Action("Index","Animal")'> 
                            <i class="fa fa-bug"></i> 
                            <div>Animal</div> 
                        </a>
                    </li>
                </ul>
            </ul>
        </div>
    </div>

    <nav class="navbar navbar-default navbar-fixed-top">
        <ul class="navbar-nav ml-auto mr-5">
            <li class="login"></li>
        </ul>
    </nav>

    <div class="container-fluid body-content">
        @RenderBody()
    </div>

    <script src="~/js/jquery-3.3.1.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="~/js/bootstrap-dialog.min.js" type="text/javascript"></script>
    <script src="~/js/select2.min.js" type="text/javascript"></script>
    <script src="~/js/es.js" type="text/javascript"></script>
    <script src="~/js/jquery.cookie.js" type="text/javascript"></script>
    <script>
        $(document).ready(function () {
            if (typeof $.cookie('token') === 'undefined') {
                console.log("no cookie");
                $(".login").html("<a href='/Authentication'><i class='fa fa-user fa-lg'></i> Ingresar</a>")
            } else {
                $(".login").html("<a href='/'><i class='fa fa-user fa-lg'></i> Salir</a>")
                $(".login").click(function (e) {
                    $.removeCookie("token", { path: '/' })
                });
            }
        });
    </script>
    @RenderSection("Scripts", required: false)

    @RenderSection("ScriptsIndex", required: false)
    <div style="clear: both;"></div>
    <footer>
        <p id="pie_pagina" style="margin: 0">Bosque Protector Prosperina</p>
    </footer>
</body>
</html>


WebApplication/Views/Shared/_Pager.cshtml
@using NonFactors.Mvc.Grid;

@model IGridPager
@{
    Int32 totalPages = Model.TotalPages;
    Int32 currentPage = Model.CurrentPage;
    Int32 firstDisplayPage = Model.FirstDisplayPage;
}

<div class="mvc-grid-pager @Model.CssClasses">
    <input class="mvc-grid-pager-rows" type="hidden" value="@Model.RowsPerPage" />
    @if (totalPages > 0)
    {
        <ul class="pagination">
            @if (currentPage > 1)
            {
                <li data-page="1"><span>&laquo;</span></li>
                <li data-page="@(currentPage - 1)"><span>&lsaquo;</span></li>
            }
            else
            {
                <li class="disabled"><span>&laquo;</span></li>
                <li class="disabled"><span>&lsaquo;</span></li>
            }
            @for (Int32 page = firstDisplayPage; page <= totalPages && page < firstDisplayPage + Model.PagesToDisplay; page++)
            {
                if (page == currentPage)
                {
                    <li class="active" data-page="@(page)"><span>@(page)</span></li>
                }
                else
                {
                    <li data-page="@(page)"><span>@(page)</span></li>
                }
            }
            @if (currentPage < totalPages)
            {
                <li data-page="@(currentPage + 1)"><span>&rsaquo;</span></li>
                <li data-page="@totalPages"><span>&raquo;</span></li>
            }
            else
            {
                <li class="disabled"><span>&rsaquo;</span></li>
                <li class="disabled"><span>&raquo;</span></li>
            }
        </ul>
    }
</div>